- spond.py
Bug fixe for #2.
Tested with this code:
```
async def main():
s = spond.Spond(username=username, password=password)
groups = await s.getGroups()
sample_group_id = groups[0]['id']
sample_group = await s.getGroup(sample_group_id)
print(sample_group['name'])
await s.clientsession.close()
loop = asyncio.get_event_loop()
loop.run_until_complete(main())
````
> Fixed: Spond.getGroup(uid) doesn't work

- spond/spond.py
Have written Numpy-style docstrings for the methods I've used in my personal projects so far.
Please let me know if e.g. any errors in described behaviour,
Thanks,
> Docstrings for most methods

- pyproject.toml
Re #26 .
3.7 is curently the latest supported version.
Seems to work OK on 3.7.9, which is the latest readily available installer.
I'm not up to date with best practice on whwre to specify this, so hope `pyproject.toml` is OK.
> Require Python >=3.7.

- .github/workflows/python-package.yml
- poetry.lock
- pyproject.toml
- tests/test_imports.py
- Add GitHub Action to install Poetry, dependencies, run (trivial for now) tests on Python 3.7 to 3.11 on Ubuntu Linux. Runs on push+pull to `main` branch.
> Add: basic CI pipeline

- ical.py
Wrapping the location parameters in get() so the example does not raise exceptions.
> Using get() in case location address is missing

- .github/workflows/python-package.yml
- poetry.lock
- pyproject.toml
Works, but time saved isn't as significant as I expected. 
Note that this has no impact on default `poetry install` for development, which installs both `dev` and `test` groups.
> 54 dont install unnecessary dependencies in ci script

- spond/spond.py
Just added an update option for events. Submitting soon a create function as well.
Cheers
> added update_event function

- .github/dependabot.yml
Dependabot script to raise PRs to update outdated packages (and Github Actions that follow GitHub repository syntax) monthly.
@Olen I can adjust to e.g. weekly if you prefer.
This won't do anything until enabled in the GitHub interface; I'll note that in #87.
> Add GitHub dependabot to handle package updates

- README.md
- spond/spond.py
@olizimmermann this relates to your https://github.com/Olen/Spond/pull/62 - do you have any comments?
> Update `send_message()` README documentation to reflect ability to start a new chat

- spond/spond.py
Description:
- function fails with  `{'message': 'Not authenticated'}`
- move to different headers and authentication solves the problem
Steps to reproduce:
- Demo code, modify uid_to_update, username and password
````
import asyncio
from config import password, username
from spond import spond
async def main():
s = spond.Spond(username=username, password=password)
uid_to_update = "xxxxxxxxxxx"
updates = {
'heading': "print",
'description': "New Description with changes",
}
try:
await s.update_event(uid_to_update, updates)
print("Event updated successfully.")
except Exception as e:
print(f"Failed to update event: {e}")
await s.clientsession.close()
loop = asyncio.new_event_loop()
asyncio.set_event_loop(loop)
asyncio.run(main())
````
Expected behavier:
- authentication is successful
> fix(authentication): switch authentication mode

- .github/workflows/python-package.yml
Although 'isort' was already in dependencies, it was not enforced in GitHub workflow.
> ci: enforce isort

- manual_test_functions.py
Uses Spond 'get' functions to summarise available data.
Uses all existing group, event, message `get_` methods.
Doesn't yet use `get_person()` (it's not as simple to test as the other get methods) or any `send_`, `update_` methods.
It also uses `print` rather than logging to console, which I can can come back to.
> Add a script to use multiple Spond functions, as a simple end-to-end manual assurance test.

- spond/spond.py
Fixes #83
Example error:
```
$ python groups.py 
Traceback (most recent call last):
File "/home/<redacted>/Spond/groups.py", line 33, in <module>
asyncio.run(main())
File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
return loop.run_until_complete(main)
File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
return future.result()
File "/home/<redacted>/Spond/groups.py", line 14, in main
groups = await s.get_groups()
File "/home/<redacted>/Spond/spond/spond.py", line 60, in wrapper
raise e
File "/home/<redacted>/Spond/spond/spond.py", line 57, in wrapper
await self.login()
File "/home/<redacted>/Spond/spond/spond.py", line 41, in login
raise AuthenticationError(err_msg)
spond.spond.AuthenticationError: Login failed. Response received: {'errorKey': …
```
> fix: meaningful error when authentication fails

- manual_test_functions.py
This part fails due to KeyError for me.
> test: manual test failing

- manual_test_functions.py
- pyproject.toml
- spond/spond.py
- tests/test_imports.py
- tests/test_spond.py
Also add coverage in manual end-to-end test suite and misc. output improvements
> Meaningful error messages when `get_group()` and `get_event()` lookups fail. 

- tests/test_spond.py
NB 1: this does not affect files in root folder, only `spond` and `test`. But that seems to be documented behaviour given code structure, and use of `pyproject.toml` for configuration.
Files in root folder can be targeted in CI/fixed later.
NB 2: ran `isort . --show-config` first to check that `profile = "black"` is picked up from `pyproject.toml` OK.
NB 3: I've done a dry run in my own fork.
> Lint existing codebase with isort + black to allow fixed CI in #116 to pass checks

- README.md
- spond/spond.py
Includes README update.
Can't think of a simple way to add tests/manual pseudo-tests for this.
> Add: `subgroup_id` parameter to `get_events()` API call

- .github/workflows/python-package.yml
I did misconfigure the black compatibility for the official isort action originally, but doesn't seem to be any documentation on how to do it correctly, and in any case it doesn't show diffs like it's supposed to (raised [isort-action #90](https://github.com/isort/isort-action/issues/90)). So I've re-implemented using command-line interface.
It should really be configured to take config from `pyproject.toml`, but that's a possible enhancement; this is restoring expected functionality.
NB isort checks are expected to fail on this PR until existing codebase has corrected isort rule run on it. I think is clearest if I do this in another PR. Will do a dry run in my own fork first...
> Fix: CI: isort GitHub action doesn't report expected issues 

- .gitignore
- README.md
- config.py.sample
- manual_test_functions.py
- spond/base.py
- spond/club.py
- spond/spond.py
- tests/test_spond.py
- transactions.py
This feature is needed for our club. However, this is a new major addition to the module as a whole (new API endpoint club).
Related to #70 as far as I can tell.
Therefore, this is just a draft to see how @Olen and @elliot-100 feel about this new feature and start a conversation around it!
I can add some example script/usage if interested
> feat: extract payments on club endpoint; feat: download attendance report; feat: update user's response to an event

- ical.py
Fixing a bug found in #119; this is leaving the long `DESCRIPTION` field unset if missing from the Spond event.
Also updated a `.format()` to f-strings.
> Fix: `ical.py` doesn't parse events without "description" field

- spond/base.py
- spond/club.py
- spond/spond.py
This PR has no run-time impact, and purposely avoids tackling any more complex typing issues (which  could be considered bugs/not-as-documented).
> feat: add type annotations for function args and returns  in `spond\`, where they are unambiguous and don't conflict with docstrings

- spond/spond.py
Amended to `numpy` standard used elsewhere in project
> fix: inconsistent docstring headings confuse type annotation checking tools

- spond/club.py
- spond/spond.py
This is a key 'missing piece' that should enable static type-checkers (e.g. mypy or IDE tools) to analyse the code fully, and help resolve more complex issues.
> Add type hints for `Spond` and `SpondClub` `__init__()` methods.

- spond/spond.py
- tests/test_spond.py
For `get_person()`, also make error message more meaningful and add 'Raises' to docstring.
> Changed: raise `KeyError` instead of `IndexError` for all failed lookup methods

- spond/spond.py
- tests/test_spond.py
This PR:
- refactors out common code from `Spond.get_event()` and `Spond.get_group()` methods to a non-public `Spond._get_entity()` method.
@dhomeier note that I have not yet touched the similar event lookup in `update_event()`, I know you are looking at this method in your #134.
- refactors the `Spond` test suite into separate classes for Event, Group and export related methods.
I may add more (which is why the heading is so general), so will keep this in draft for now.
> Refactor: extract duplicated code and reorder tests

- README.md
- manual_test_functions.py
- spond/spond.py
This PR:
- Re #144: Adds an optional `max_chats` parameter to `Spond.get_messages()`; defaults to 100. Previously up to 10 chats were returned.
- Re #145: #Changes `Spond.get_messages()` so it populates `Spond.messages` in line with other `get_{multiple_items_from_api}()` methods.
- Updates `manual_test_functions` to use the new parameter (and extracts all `max` values to constants)
- Where possible, uses the term 'chats' instead of `messages' which is more accurate (a chat can contain many messages) but *not* to the extent of changing the API - that can be discussed later.
> `Spond.get_messages`: add `max_chats` parameter (default 100) and populate `Spond.messages`.

- spond/spond.py
This PR:
- Corrects docstrings and return type hints in `Spond.spond` where API retrieval functions may return `None`
- Simplifies those docstrings and makes them more consistent
- Doesn't address similar issues in `Spond.club` as there are key differences with the code, and I don't have any transactions to test
It should not have any effect at all at runtime.
> Docs: fix documentation and type hints where functions may return `None`

- manual_test_functions.py
- spond/__init__.py
- spond/club.py
- spond/spond.py
- tests/test_spond.py
This PR makes several changes to type hints and docstrings. No run-time checking is done and there should be zero runtime impact.
- Modernises existing `Optional[Type]` pattern hints to Python >= 3.10 `Type | None` pattern
- Refactors type hints, by extracting a very simple `JSONDict` type alias to be used for `dicts` to be passed to/from JSON. It's equivalent to `Dict[str,  Any]`.
Together these mean that e.g. `Optional[list[Dict[str, Any]]]` can be written more simply, as `list[JSONDict] | None`.
- Adds `list[JSONDict] | None` hint to relevant `Spond`, `SpondClub` attributes. Also adds relevant `JSONDict` hints to test fixtures and parameters.
NB: This does not add `JSONDict` hints to returns from `Spond.send_message()` or `Spond.update_event()` as these need a bit more thought - both …
> Correct documentation and type hints where functions may return None

- manual_test_functions.py
This PR moves the `JSONDict` import out of a type-checking-only block.
> Fixes: NameError: name 'JSONDict' is not defined

- .github/workflows/python-package.yml
- pyproject.toml
This PR:
- Adds newly released Python 3.13 to CI matrix and to `black` `target-versions`
- Removes end-of-life Python 3.8 from CI matrix and from `black` `target-versions`. This is primarily because latest `black` no longer supports 3.8
- Bumps dev-dep `black` to latest to ensure same behaviour in dev and CI 
I've done a quick check and there don't appear to be any obvious code upgrades to be made by dropping 3.8.
3.9 did introduce the `|` Union operator, but that's already used in the code via `__future__ import annotations`.
> Add support for Python 3.13, drop support for Python 3.8

- attendance.py
This PR updates the `get_events()` call to use keyword params
> Fix: attendance.py example script exits with error if --from or --to params are used

- .gitignore
- attendance.py
Hi,
I came across two issues when using your project. One is about sanitising filenames based on events (for attendance) where certain special characters allowed by Spond in event names (e.g. a forward slash) would lead to unexpected behaviour or problems. I've added some code to handle these (however this might need to be reviewed for copyright as I found it somewhere but it was mentioned that it might have been taken from Django).
The other change is to handle the situation when member information is not available which lead to a crash. I'm not sure what is wrong in the account on Spond but I've included some handling for the situation when the member based on ID cannot be found. In that case the output will simply be the member guid.
The last (or actually first) commit (adding a folder …
> Sanitize filenames and handle member issues in `attendance.py` example script

- spond/spond.py
This PR refactors the relevant code to use `self._get_entity(self._EVENT, uid)` to  ensure an error is raised when the uid is not matched, and prevent any event modification.
> Fix: Spond.update_events(uid...) will modify or overwrite another event, if no event matching uid exists bug

- spond/__init__.py
- spond/base.py
- spond/spond.py
As per issue #162, this PR marks these members as non-public, as they are not for end-user use:
```
spond.spond.Spond.chat_url -> spond.spond.Spond._chat_url
spond.spond.Spond.auth -> spond.spond.Spond._auth
spond.spond.Spond.login_chat() -> spond.spond.Spond._login_chat()
```
and moves this, as it should be public, but is currently in a module that only exists to hold the non-public `_SpondBase` class:
```
spond.base.AuthenticationError -> spond.AuthenticationError
```
> Mark members as non-public and move public AuthenticationError

- .github/workflows/python-package.yml
- attendance.py
- groups.py
- ical.py
- manual_test_functions.py
- pyproject.toml
- spond/club.py
- spond/spond.py
- tests/test_spond.py
- transactions.py
This PR effectively replaces `isort` + `black` with `ruff check`/`ruff format`, including in CI.
- It enforces `ruff`'s formatting rules - these differ slightly from `black`'s, but I don't think it's worth worrying about that.
- It also enforces a few basic linting rules that the code already meets (a subset of those suggested at https://docs.astral.sh/ruff/linter/#rule-selection). These can be extended in future.
How to use at CLI when developing:
- Use `ruff check --fix` to autolint, instead of `isort .` to just sort imports
- Use `ruff format` instead of `black .`
> Use `ruff` instead of `isort` and `black` and enforce basic linting

- spond/spond.py
This PR enhances the functionality of `Spond.get_events()` by adding a new parameter, `include_hidden`, which allows fetching hidden events that are visible to users with at least admin permissions, addressing the feature request in issue #164.
**Note**: The `include_hidden` parameter is only supported if a `group_id` is provided. If used without `group_id`, the Spond API will respond with an error: 
> 'includeHidden' filter is only available inside a group
Therefore, this parameter is included in the request only when both `group_id` and `include_hidden=True` are specified. Otherwise, the method behaves as it did previously.
- **New Parameter**: Added `include_hidden` to the method signature.
- **Update Docstring**: Tried to match the current style of the docstring.
- **API Parameter**: …
> Add include_hidden parameter to `Spond.get_events()`

- .github/workflows/python-package.yml
- pyproject.toml
This PR changes the `python-package` GitHub workflow to install and `poetry run ruff...` explicitly, rather than via GitHub action.
This makes things simpler: we now only need a single dev-dependency group instead of two, and CI will now install the `ruff` version specified there.
It also updates the CI `pytest` step to use `poetry run...` to be consistent.
> Fix #174: CI ruff step emits warning about version

- manual_test_functions.py
- pyproject.toml
- spond/__init__.py
- spond/spond.py
- tests/test_spond.py
Building on https://github.com/Olen/Spond/pull/152, this PR:
- Completes return hints for public functions, methods in the main module and enforces their presence, i.e. new code in the main module must have return types to pass CI. Some of these go along with what docstrings say is returned, not what may actually be returned. But sorting that is one for a different PR.
- Adds additional return types in tests, but this is still incomplete and not enforced.
It should have zero runtime effect.
Note no actual type checking is enforced yet.
> Typing: complete and enforce presence of return type annotations for public functions in main module

- manual_test_functions.py
Fixes #194 by moving `import JSONDict` out of a type-checking block.
> fix: 194 JSONDict import incorrectly in type-checking block
